# Generated by Django 5.2 on 2025-04-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(help_text='用户唯一登录凭证', max_length=30, unique=True, verbose_name='账号')),
                ('password', models.CharField(help_text='建议使用PBKDF2加密存储', max_length=128, verbose_name='密码')),
                ('nickname', models.CharField(blank=True, default='新用户', max_length=50, verbose_name='昵称')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='football.article')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.user', to_field='account', verbose_name='评论者')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.user', to_field='account', verbose_name='作者'),
        ),
    ]
