# Generated by Django 5.2 on 2025-04-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动详情')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('datetime', models.DateTimeField(verbose_name='活动开始时间')),
                ('required_players', models.PositiveIntegerField(verbose_name='目标人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.user', verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='football.match', verbose_name='约战活动')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_registrations', to='football.user', verbose_name='报名用户')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
