# Generated by Django 5.2 on 2025-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0002_match_matchregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchregistration",
            name="name",
            field=models.CharField(
                default="匿名用户", max_length=100, verbose_name="姓名"
            ),
        ),
        migrations.AddField(
            model_name="matchregistration",
            name="phone",
            field=models.CharField(
                default="无电话", max_length=20, verbose_name="电话号码"
            ),
        ),
    ]
